"""add due_date to tasks

Revision ID: 7b7a84955f09
Revises: defc45e34c90
Create Date: 2026-02-12 18:04:50.764942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7a84955f09'
down_revision: Union[str, Sequence[str], None] = 'defc45e34c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_orm', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks_orm', 'due_date')
    # ### end Alembic commands ###
